def broken_func(
    return 1
